events {
    worker_connections 1024;
}

http {
    upstream agent_stack {
        # Agent service name in docker-compose. 
        # Docker DNS handles the multiple replicas automatically.
        server agent:8000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://agent_stack;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
            # Xóa header Server để bảo mật
            proxy_hide_header Server;
        }
    }
}
